/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pboproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Makhluk Hidup
 */
public class FAbout extends javax.swing.JFrame {

    /**
     * Creates new form FAbout
     */
    public FAbout() {
        setUndecorated(true);  // Menghilangkan dekorasi jendela (termasuk tombol close, minimize, dan maximize)
        initComponents();
        setLocationRelativeTo(null); // Agar jendela muncul di tengah layar
    }
    
    private void goToTransit() {
        // Panggil frame baru
        FTransit tabTransit = new FTransit();
        tabTransit.setVisible(true);

        // Tutup halaman saat ini
        dispose();
    }
    
    private void goToMain() {
        // Panggil frame baru
        FMain tabMain = new FMain();
        tabMain.setVisible(true);

        // Tutup halaman saat ini
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        lblMain = new javax.swing.JLabel();
        lblTransit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image 5.png"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, 80));

        btLogout.setBackground(new java.awt.Color(0, 102, 153));
        btLogout.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        btLogout.setForeground(new java.awt.Color(255, 255, 255));
        btLogout.setText("Logout");
        btLogout.setBorder(null);
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 445, 110, 37));

        lblMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMouseClicked(evt);
            }
        });
        getContentPane().add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 80));

        lblTransit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTransit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransitMouseClicked(evt);
            }
        });
        getContentPane().add(lblTransit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AboutUs.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin ingin Logout",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            FLogin formLogin = new FLogin();  // Pastikan FLogin adalah kelas lain yang valid
            formLogin.setVisible(true);
            dispose(); // Tutup form FMain
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void lblTransitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransitMouseClicked
        // TODO add your handling code here:
        try {
            Thread.sleep(300); // Delay 2 detik (2000 ms)
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        goToTransit();
    }//GEN-LAST:event_lblTransitMouseClicked

    private void lblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMouseClicked
        // TODO add your handling code here:
        try {
            Thread.sleep(300); // Delay 2 detik (2000 ms)
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        goToMain();
    }//GEN-LAST:event_lblMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAbout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblTransit;
    // End of variables declaration//GEN-END:variables
}
